import { Metadata } from "next";
import Provider from "../core/Provider";

export const metadata: Metadata = {
   title: "Next.js",
   description: "Generated by Next.js",
};

interface LayoutProps {
   children: React.ReactNode;
}

function Layout({ children }: LayoutProps) {
   return <Provider>{children}</Provider>;
}

export default Layout;
